#!/bin/bash
#
# LSF batch script to run an MPI application
#
#BSUB -P P86850055           # project code
#BSUB -W 01:00               # wall-clock time (hrs:mins)
#BSUB -n 64                  # number of tasks in job         
#BSUB -R "span[ptile=16]"    # run 16 MPI tasks per node
#BSUB -J main                # job name
#BSUB -o ./out/main.%J.out   # output file name in which %J is replaced by the job ID
#BSUB -e ./err/main.%J.err   # error file name in which %J is replaced by the job ID
#BSUB -q small               # queue

#run the executable
mpirun.lsf ./main
